version: '3'

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jpark2/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jpark2/data/wordpress
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - inception_network
    env_file:
      - ./.env
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    depends_on:
      - mariadb
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - ./.env
    restart: always

networks:
  inception_network:
    driver: bridge
